import { MenuData } from "./types";

export const menuData: MenuData = {
  categories: [
    { id: "cocteles", label: "Cócteles & Sodas" },
    { id: "bebidas", label: "Cervezas & Más" },
    { id: "licores", label: "Licores & Vinos" },
    { id: "comidas", label: "Comidas" },
  ],
  items: {
    cocteles: [
      // --- CÓCTELES DE AUTOR ---
      {
        id: "c-autor-1",
        name: "Caricia Oscura",
        description: "Ron, zumo de limón, clara de huevo, syrup de frutos rojos.",
        price: "$18.000",
        type: "Autor",
        image: "/assets/caricia-oscura.jpeg",
      },
      {
        id: "c-autor-2",
        name: "Tentáculo",
        description: "Tequila, zumo de limón, Curaçao.",
        price: "$20.000",
        type: "Autor",
        image: "/assets/tentaculo.jpeg",
      },
      {
        id: "c-autor-3",
        name: "Veneno",
        description: "Ron blanco, zumo de limón, soda, monín, granadina, Curaçao, syrup de frutos verdes, perlas explosivas.",
        price: "$30.000",
        type: "Autor",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "c-autor-4",
        name: "Penumbra",
        description: "Aguardiente, zumo de naranja, Curaçao, syrup de café.",
        price: "$20.000",
        type: "Autor",
        image: "/assets/penumbra.jpeg",
      },
      {
        id: "c-autor-5",
        name: "Sombra Marina",
        description: "Ginebra, syrup de sandía, soda, Curaçao, arándanos.",
        price: "$22.000",
        type: "Autor",
        image: "/assets/sombra-marina.jpeg",
      },
      // --- CÓCTELES TRADICIONALES ---
      {
        id: "c-trad-1",
        name: "Margarita",
        description: "Tequila, triple sec, syrup simple, zumo de limón.",
        price: "$18.000",
        type: "Tradicional",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "c-trad-2",
        name: "Martini",
        description: "Vodka, vermut, aceitunas.",
        price: "$25.000",
        type: "Tradicional",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "c-trad-3",
        name: "Negroni",
        description: "Ginebra, Aperol Spritz, Jägermeister.",
        price: "$40.000",
        type: "Tradicional",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "c-trad-4",
        name: "Mojito",
        description: "Ron blanco, soda, hierbabuena, zumo de limón.",
        price: "$20.000",
        type: "Tradicional",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "c-trad-5",
        name: "Piña Colada",
        description: "Ron, leche de coco, helado de vainilla, piña, zumo de limón, coco rayado.",
        price: "$24.000",
        type: "Tradicional",
        image: "/assets/piña-colada.jpeg",
      },
      // --- PARA COMPARTIR ---
      {
        id: "c-comp-1",
        name: "Pecera Ritual de Gorgona",
        description: "Vodka, ron blanco, zumo de naranja, granadina, Coca-cola, zumo de limón, maracuyá.",
        price: "$65.000",
        note: "Para 4-5 personas. Tamaño Mini (1-2 personas): $30.000",
        type: "Para Compartir",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "c-comp-2",
        name: "Sangría Sangre del Olimpo",
        description: "Vodka, vino, soda, manzana verde, manzana roja, fresa, pera, naranja, zumo de limón, granadina.",
        price: "$70.000",
        note: "Para 4-5 personas.",
        type: "Para Compartir",
        image: "/assets/placeholder.jpg",
      },
      // --- SODAS SABORIZADAS ---
      {
        id: "soda-1",
        name: "Soda de Maracumango",
        description: "Soda, syrup de maracumango, zumo de limón, arándanos, mango, maracuyá.",
        price: "$15.000",
        type: "Soda",
        image: "/assets/soda-maracumango.jpeg",
      },
      {
        id: "soda-2",
        name: "Soda Hierbabuena y Piña",
        description: "Soda, syrup de hierbabuena y piña, zumo de limón, arándanos, hierbabuena, piña.",
        price: "$15.000",
        type: "Soda",
        image: "/assets/soda-piña-hierba-buena.jpeg",
      },
      {
        id: "soda-3",
        name: "Soda de Frutos Rojos",
        description: "Soda, syrup de frutos rojos, zumo de limón, arándanos, fresa, cerezas.",
        price: "$15.000",
        type: "Soda",
        image: "/assets/soda-frutos-rojos.jpeg",
      }
    ],
    licores: [
      // --- MICHELADAS ---
      {
        id: "l-mich-1",
        name: "Michelada Clásica",
        description: "Águila, Águila Light, Poker, Budweiser, Redd's, Heineken, Costeña, Coronita.",
        price: "$12.000",
        type: "Michelada",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "l-mich-2",
        name: "Michelada Premium",
        description: "Club Colombia Dorada, Stella Artois.",
        price: "$15.000",
        type: "Michelada",
        image: "/assets/placeholder.jpg",
      },
      // --- VINOS ---
      {
        id: "l-vino-1",
        name: "Vino Tinto Artesanal",
        description: "Vino de la casa.",
        price: "$50.000",
        note: "Botella",
        type: "Vino",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "l-vino-2",
        name: "Vino de Cacao",
        description: "Vino dulce artesanal.",
        price: "$40.000",
        note: "Botella",
        type: "Vino",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "l-vino-3",
        name: "Vino de Café",
        description: "Vino dulce artesanal.",
        price: "$40.000",
        note: "Botella",
        type: "Vino",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "l-vino-4",
        name: "Vino Tinto, Blanco, Rosado",
        description: "Reserva - Reservado - Joven.",
        price: "$80.000",
        note: "Botella (Rango: $80.000 - $100.000)",
        type: "Vino",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "l-vino-5",
        name: "Copa de Vino",
        description: "Vino de la casa por copa.",
        price: "$15.000",
        type: "Vino",
        image: "/assets/placeholder.jpg",
      },
      // --- LICORES FUERTES ---
      {
        id: "l-licor-1",
        name: "Aguardiente Amarillo de Manzanares",
        description: "Tradicional.",
        price: "Desde $6.000",
        note: "Trago: $6.000 | Media: $45.000 | Botella: $80.000",
        type: "Aguardiente",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "l-licor-2",
        name: "Aguardiente Doble Anis",
        description: "Azul o Verde.",
        price: "Desde $6.000",
        note: "Trago: $6.000 | Media: $45.000",
        type: "Aguardiente",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "l-licor-3",
        name: "Ron Viejo de Caldas",
        description: "Ron tradicional.",
        price: "Desde $6.000",
        note: "Trago: $6.000 | Media: $50.000",
        type: "Ron",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "l-licor-4",
        name: "Ron Bacardi Blanco",
        description: "Ron blanco ideal para mezclar.",
        price: "Desde $7.000",
        note: "Trago: $7.000 | Botella: $85.000",
        type: "Ron",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "l-licor-5",
        name: "Tequila",
        description: "Tequila tradicional.",
        price: "Desde $7.000",
        note: "Trago: $7.000 | Botella: $70.000",
        type: "Tequila",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "l-licor-6",
        name: "Vodka",
        description: "Vodka clásico.",
        price: "Desde $7.000",
        note: "Trago: $7.000 | Botella: $65.000",
        type: "Vodka",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "l-licor-7",
        name: "Ginebra / Gin Tonic",
        description: "Ginebra premium.",
        price: "Desde $7.000",
        note: "Trago: $7.000 | Botella: $65.000",
        type: "Ginebra",
        image: "/assets/placeholder.jpg",
      },
      {
        id: "l-licor-8",
        name: "Jägermeister",
        description: "Licor de hierbas.",
        price: "Desde $12.000",
        note: "Trago: $12.000 | Botella: $150.000",
        type: "Licor",
        image: "/assets/placeholder.jpg",
      }
    ],
    bebidas: [
      {
        id: "b-cer-1",
        name: "Águila - Poker",
        description: "Cerveza nacional.",
        price: "$4.500",
        type: "Cerveza",
        image: "/assets/cervezas.jpeg",
      },
      {
        id: "b-cer-2",
        name: "Costeña",
        description: "Cerveza nacional.",
        price: "$4.000",
        type: "Cerveza",
        image: "/assets/costeña.jpeg",
      },
      {
        id: "b-cer-3",
        name: "Águila Light, Budweiser, Redd's, Heineken",
        description: "Cervezas importadas y ligeras.",
        price: "$5.000",
        type: "Cerveza",
        image: "/assets/reds.jpeg",
      },
      {
        id: "b-cer-4",
        name: "Coronita",
        description: "Cerveza importada.",
        price: "$6.000",
        type: "Cerveza",
        image: "/assets/coronita.jpeg",
      },
      {
        id: "b-cer-5",
        name: "Stella Artois",
        description: "Cerveza importada.",
        price: "$7.000",
        type: "Cerveza",
        image: "/assets/stella.jpeg",
      },
      {
        id: "b-cer-6",
        name: "Club Colombia Dorada",
        description: "Cerveza premium nacional.",
        price: "$8.000",
        type: "Cerveza",
        image: "/assets/club.jpeg",
      },
      {
        id: "b-hid-1",
        name: "Gatorade",
        description: "Bebida hidratante.",
        price: "$5.000",
        type: "Hidratante",
        image: "/assets/gatorade.jpeg",
      },
      {
        id: "b-hid-2",
        name: "Electrolit",
        description: "Bebida hidratante.",
        price: "$10.000",
        type: "Hidratante",
        image: "/assets/electrolit.jpeg",
      },
      {
        id: "b-hid-3",
        name: "Agua",
        description: "Agua en botella.",
        price: "$2.000",
        type: "Hidratante",
        image: "/assets/agua.jpeg",
      },
      {
        id: "b-hid-4",
        name: "Soda",
        description: "Soda en botella.",
        price: "$3.000",
        type: "Hidratante",
        image: "/assets/soda.jpeg",
      },
      {
        id: "b-gas-1",
        name: "Personal - Coca-Cola",
        description: "Gaseosa personal.",
        price: "$4.000",
        type: "Gaseosa",
        image: "/assets/coca.jpeg",
      },
      {
        id: "b-gas-2",
        name: "Soda Michelada",
        description: "Bebida refrescante.",
        price: "$10.000",
        type: "Gaseosa",
        image: "/assets/soda-saborisada.jpeg",
      }
    ],
  comidas: [
      {
        id: "f-1",
        name: "Picada",
        description: "Pollo, cerdo, chorizo, costilla, papa criolla, papas a la francesa, rapiyuca.",
        price: "$26.000",
        image: "/assets/picada.jpeg",
      },
      {
        id: "f-2",
        name: "Tacos Mixtos",
        description: "Res y pollo.",
        price: "$15.000",
        image: "/assets/tacos.jpeg",
      },
      {
        id: "f-3",
        name: "Pincho de Pollo",
        description: "Acompañado de arepa.",
        price: "$15.000",
        image: "/assets/pincho.jpeg",
      },
      {
        id: "f-4",
        name: "Pechuga Gratinada",
        description: "Acompañada de papas a la francesa.",
        price: "$19.000",
        image: "/assets/pechuga.jpeg",
      },
      {
        id: "f-5",
        name: "Costillas BBQ",
        description: "Acompañadas de patacones.",
        price: "$19.000",
        image: "/assets/costillas.jpeg",
      },
      {
        id: "f-6",
        name: "Hamburguesa con Pan",
        description: "Carne de res, tomate, lechuga, queso, cebolla caramelizada, salsas.",
        price: "$13.000",
        image: "/assets/hamburguesa.jpeg",
      },
      {
        id: "f-7",
        name: "Chorizo Artesanal",
        description: "Acompañado de arepa.",
        price: "$16.000",
        image: "/assets/chorizo.jpeg",
      },
      {
        id: "f-8",
        name: "Lomo de Cerdo",
        description: "Acompañado de patacones.",
        price: "$19.000",
        image: "/assets/cerdo.jpeg",
      },
      {
        id: "f-9",
        name: "Lomo de Res",
        description: "Acompañado de patacones.",
        price: "$19.000",
        image: "/assets/res.jpeg",
      },
      {
        id: "f-10",
        name: "Pizza Personal",
        description: "Sabores: Pollo con champiñones, mixta, hawaiana, mexicana.",
        price: "$17.000",
        image: "/assets/pizza.jpeg",
      },
      {
        id: "f-11",
        name: "Porción de Papas",
        description: "Papas a la francesa.",
        price: "$6.000",
        image: "/assets/papas.jpeg",
      }
    ],
  },
};